/*
 * Copyright (c) 2020 - present Cloudogu GmbH
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://www.gnu.org/licenses/.
 */

plugins {
  id 'org.scm-manager.smp' version '0.20.0'
}

dependencies {
}

scmPlugin {
  scmVersion = "2.15.0"
  isScm4Compatible = true
  displayName = "Json Metrics"
  description = "Provides SCM-Manager metrics as json"
  author = "Cloudogu GmbH"
  category = "Administration"
}
